### ISSUE TITLE
Cannot read property 'loc' of undefined with indent rule

### ISSUE THREAD

**Issue by mdebruijne** [eslint/typescript-eslint-parser#309]
**What version of TypeScript are you using?**
2.3.4

**What version of `typescript-eslint-parser` are you using?**
3.0.0

**What code were you trying to parse?**
echo "const" | eslint --stdin --no-eslintrc --parser typescript-eslint-parser --rule '"indent": ["error"]'

**What did you expect to happen?**
Same result as with default parser; echo "const" | eslint --stdin --no-eslintrc --rule '"indent": ["error"]'

  1:1  error  Parsing error: The keyword 'const' is reserved

**What happened?**
Cannot read property 'loc' of undefined                                                                                                                                                        
TypeError: Cannot read property 'loc' of undefined                                                                                                                                             
    at EventEmitter.VariableDeclaration (node_modules/eslint/lib/rules/indent.js:1000:68)                                                               
    at emitOne (events.js:115:13)                                                                                                                                                              
    at EventEmitter.emit (events.js:210:7)                                                                                                                                                     
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/util/node-event-generator.js:265:26)                                                   
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/util/node-event-generator.js:294:22)                                                  
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:308:14)                                                       
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)                                             
    at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:98:23)                                                  
    at Traverser.enter (node_modules/eslint/lib/eslint.js:929:36)                                                                                       
    at Traverser.__execute (node_modules/estraverse/estraverse.js:397:31)

**Comment by JamesHenry** [comment]
@mdebruijne What version of node and ESLint are you using?

**Comment by soda0289** [comment]
I can reproduce the problem using node 6.10 and eslint 3.19. The problem goes away in eslint v4 but this is still a bug in my opinion.

Currently this parser converts an AST by running the code through TypeScript parser and then converting it to an ESTree AST. The typescript parser does not report syntax errors during the initial AST creation. This means code like:
`const` or `let f = 1; let f = 2;` 
Do not throw errors even when they should, since they are invalid. 

Typescript parser will throw errors when we enable certain error conditions, or transpile to javascript, but this also changes the AST that is produced. I can look into ways to copy the AST after initial conversion and then turn on the extra error handlers for syntax and semantic errors. This should allow for this parser to throw errors for invalid JavaScript and even invalid TypeScript. Something we do not currently do but is the expected behavior.

**Comment by mdebruijne** [comment]
@JamesHenry I am using Node version 8.0.0 and ESLint version 3.19.0

@soda0289 It would be great if you are able to catch the error, because uncaught errors are being propagated to Visual Studio Code integration (and maybe other editors/IDEs) which result in an intrusive popup every time someone types `const` for example.

**Comment by wesleymostien** [comment]
I have this too, very annoying... any possible temp fix ?

**Comment by mdebruijne** [comment]
@wesleymostien This has been fixed in ESLint version 4.x

**Comment by wesleymostien** [comment]
sorry @mdebruijne , I have eslint 4.9.0 + typescript-eslint-parser 8.0.0 and I still have this issue.

**Comment by mdebruijne** [comment]
@wesleymostien I have tested this with the current versions (ESLint 4.9.0, typescript-eslint-parser 8.0.1) and you are correct, the problem has returned. I have opened a project with older versions (ESLint 4.0.0, typescript-eslint-parser 3.0.0) and with these version the problem was resolved. Somewhere between these releases the problem came back.

**Comment by wesleymostien** [comment]
thanks for confirming @mdebruijne

**Comment by JamesHenry** [comment]
I'm going to close this due to lack of activity.

We now have a brand new way of running integration tests for this project, which allows for complex setups to be reproduced in isolation: https://github.com/eslint/typescript-eslint-parser#integration-tests

If this is still an issue for you using the latest version, please create a failing integration test for it and open a new issue to discuss.

Thanks!
